module.exports = {
  BRANCHES: "branches",
  CAREER_JOURNEYS: "career_journeys",
  CAREER_MOBILITIES: "career_mobilities",
  COMPETENCIES: "competencies",
  DEPARTMENTS: "departments",
  DIPLOMAS: "diplomas",
  DIRECTORATES: "directorates",
  DIVISIONS: "divisions",
  EDUCATION: "education",
  EMPLOYMENT_STATUSES: "employment_statuses",
  GROUP_LEVELS: "group_levels",
  KEY_COMPETENCIES: "key_competencies",
  ORGANIZATIONS: "organizations",
  SCHOOLS: "schools",
  SECOND_LANGUAGE_PROFICIENCIES: "second_language_proficiencies",
  SECTORS: "sectors",
  SECURITY_CLEARANCES: "security_clearances",
  SKILLS: "skills",
  TALENT_MATRIX_RESULTS: "talent_matrix_results",
  USER_COMPETENCIES: "user_competencies",
  USER_DEVELOPMENTAL_GOALS: "user_developmental_goals",
  USER_ORGANIZATIONS: "user_organizations",
  USER_PROJECTS: "user_projects",
  USER_SKILLS: "user_skills",
  USERS: "user"
};
